### PR TITLE
Refresh task list after task creation in project/working group view

### LINKED ISSUE #805: Opportunity is not listed after creation in the group details
When I add a new opportunity in a group, the view is not refreshed with the new opportunity.

Steps to reproduce:
1. Open a group details (https://midas-dev.18f.us/projects/9)
2. Click "Add Opportunity"
3. Fill out all the information to create an opportunity
4. Click "Create"
5. Notice the opportunity is not listed in the "Available Opportunities"
6. Refresh the page
7. Notice the opportunity is listed

### PR DESCRIPTION
**Pull request by brandtheisey**
Causes a task list refresh after task creation in the project / working group view.
Fixes #805

Thanks for reporting this @nhu313!

### CODE REVIEW

File: assets/js/backbone/apps/tasks/list/controllers/task_list_controller.js [hunk 1]
```diff
@@ -69,7 +69,11 @@ TaskList = Backbone.View.extend({
   renderTaskCollectionView: function () {
     var self = this;
 
-    if (this.taskCollectionView) this.taskCollectionView.cleanup();
+    this.listenTo(this.collection, "task:save:success", function (model) {
+      self.requestTasksCollectionData();
+    });
+
+  if (this.taskCollectionView) this.taskCollectionView.cleanup();
```
Comment (dhcole) [inline assets/js/backbone/apps/tasks/list/controllers/task_list_controller.js]: Looks like the whitespace is off here -- do you mind indenting one level? (sorry to nit pick... helps to keep the code readable)

**Comment by brandtheisey** [comment]
updated

**Comment by dhcole** [comment]
:+1:
